### PR TITLE
switch to README.rst for PyPI

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by Gr1N** [comment]
Oh.. I hate rst format, but I understand...

**Comment by Gr1N** [comment]
Could you please remove README.md from repo? I don't think that I want to support two readme files.

**Comment by graingert** [comment]
woops, I meant to. That was a rebaseo

**Comment by Gr1N** [comment]
Looks good https://pypi.python.org/pypi/asyncio-ipython-magic
Thanks.

**Pull request merged**
